---
title: "GT_Datawork"
author: "migs" 
date: "2024-06-17"
output: github_document
---

```{r library, echo = T }
library(ggplot2)
library(magrittr)
library(readr)
library(RCurl)
library(tidyr)
library(tidyverse)
library(Evapotranspiration)
```


```{r data import, echo = F}
#Plot References Data
plot_references <- read.csv("~/GitHub/GillData/Plot_References.csv", na.strings="#N/A")
view(plot_references)

#Soil Sensor Data
logger_A_data <- read.csv("~/GitHub/GillData/logger_A_data.csv", na.strings="#N/A")
logger_C_data <- read.csv("~/GitHub/GillData/logger_C_data.csv", na.strings="#N/A")
logger_D_data <- read.csv("~/GitHub/GillData/logger_D_data.csv", na.strings="#N/A")
logger_E_data <- read.csv("~/GitHub/GillData/logger_E_data.csv", na.strings="#N/A")
logger_F_data <- read.csv("~/GitHub/GillData/logger_F_data.csv", na.strings="#N/A")
logger_G_data <- read.csv("~/GitHub/GillData/logger_G_data.csv", na.strings="#N/A")
#head(logger_A_data)

#Soil Core Data
Soilcore_Data <- read.csv("~/GitHub/GillData/Soilcore_Data.csv")
view(Soilcore_Data)

#Biomass Data
Biomass_Data <- read.csv("~/GitHub/GillData/Biomass_Data.csv")
view(Biomass_Data)

#Weather Data
Weather_Data <- read.csv("~/GitHub/GillData/UC_Gill_Tract_Weather_Data.csv")
view(Weather_Data)
```

```{r labeling loggers and data hygeine, echo = F}
#Logger A
logger_A_data <- logger_A_data %>% 
  mutate(logger = "A") %>% 
  rename(Datetimes = "z6.07504")
#view(logger_A_data)

#Logger C
logger_C_data <- logger_C_data %>% 
  mutate(logger = "C") %>% 
  rename(Datetimes = "z6.07590")
#view(logger_C_data)

#Logger D
logger_D_data <- logger_D_data %>% 
  mutate(logger = "D") %>% 
  rename(Datetimes = "z6.07591")
#view(logger_D_data)

#Logger E
logger_E_data <- logger_E_data %>% 
  mutate(logger = "E") %>% 
  rename(Datetimes = "z6.07506")
#view(logger_E_data)

#Logger F
logger_F_data <- logger_F_data %>% 
  mutate(logger = "F") %>% 
  rename(Datetimes = "z6.07592")
#view(logger_F_data)

#Logger G
logger_G_data <- logger_G_data %>% 
  mutate(logger = "G") %>% 
  rename(Datetimes = "z6.07509")
#view(logger_G_data)

#Combining all loggers' data
combined_data <- rbind(logger_A_data, logger_C_data, logger_D_data, logger_E_data, logger_F_data, logger_G_data)
#view(combined_data)

#Data Joining using plot references
#Biomass Data
Biomass_Data <- full_join(Biomass_Data, plot_references, by = 'Plot')
#view(Biomass_Data)

#Soilcore Data
Soilcore_Data <- full_join(Soilcore_Data, plot_references, by = 'Plot')
view(Soilcore_Data)

```

```{r data transforming, echo = F}
#transposing  data
unique_columns <- c("Port.1", "Port.2", "Port.3", "Port.4", "Port.5", "Port.6")

combined_transposed <- pivot_longer(combined_data, cols = all_of(unique_columns), names_to = "Port", values_to = "WaterAmt")
#view(combined_transposed)

#Conversion char to POSIXct (unix time)
combined_transposed$Datetimes <- as.POSIXct(combined_transposed$Datetimes, format = "%m/%d/%y %H:%M", tz = "")
#class(combined_transposed$Datetimes)

#Selecting Columns
combined_transposed <- combined_transposed %>% 
  select(Datetimes, logger, Port, WaterAmt)
#view(combined_transposed)

#Adding in Depths
combined_transposed <- combined_transposed %>% 
  mutate(Depth.cm =case_when(
    Port == "Port.1" ~ "15",
    Port == "Port.2" ~ "30",
    Port == "Port.3" ~ "60",
    Port == "Port.4" ~ "15",
    Port == "Port.5" ~ "30",
    Port == "Port.6" ~ "60"
  ))
#view(combined_transposed)

#Weather Data Fixing
#Conversion char to POSIXct (unix time)
Weather_Data$Datetimes <- as.POSIXct(Weather_Data$Datetime, format = "%m/%d/%y %H:%M", tz = "")
#class(Weather_Data$Datetimes)

```

```{r Adding in Treatments, Fallow Y/N, echo = F}
#Adding Treatments
Sensor_Data <- combined_transposed %>% 
  mutate(Treatment = case_when(
    #Logger A
      ((Port == "Port.1" | Port == "Port.2" | Port == "Port.3") & logger == "A") ~ "Rye-Radish",
      ((Port == "Port.4" | Port == "Port.5" | Port == "Port.6") & logger == "A") ~ "Rye-Vetch",
    #Logger C
      ((Port == "Port.1" | Port == "Port.2" | Port == "Port.3") & logger == "C") ~ "Fallow",
      ((Port == "Port.4" | Port == "Port.5" | Port == "Port.6") & logger == "C") ~ "4-seed",
    #Logger D
      ((Port == "Port.1" | Port == "Port.2" | Port == "Port.3") & logger == "D") ~ "Rye Mono",
      ((Port == "Port.4" | Port == "Port.5" | Port == "Port.6") & logger == "D") ~ "Rye-Vetch",    
    #Logger E
      ((Port == "Port.1" | Port == "Port.2" | Port == "Port.3") & logger == "E") ~ "Rye-Vetch",
      ((Port == "Port.4" | Port == "Port.5" | Port == "Port.6") & logger == "E") ~ "Fallow",    
    #Logger F
      ((Port == "Port.1" | Port == "Port.2" | Port == "Port.3") & logger == "F") ~ "4-seed",
      ((Port == "Port.4" | Port == "Port.5" | Port == "Port.6") & logger == "F") ~ "Rye Mono",
    #Logger G
      ((Port == "Port.1" | Port == "Port.2" | Port == "Port.3") & logger == "G") ~ "4-seed",
      ((Port == "Port.4" | Port == "Port.5" | Port == "Port.6") & logger == "G") ~ "Fallow",
    TRUE ~ NA_character_
  )) %>% 
  mutate(Fallow_YN = ifelse(Treatment == "Fallow", "Y", "N"))
view(Sensor_Data)
```


```{r basic visualizations, echo = T}
#Timestamp vs. Water Content, color = Depth
ggplot(Sensor_Data, aes(x = Datetimes, y = WaterAmt, color = Depth.cm)) +
  geom_smooth(na.rm = T) + 
 # geom_point() +
  scale_y_continuous(limits = c(0.18, 0.45)) ##Removes negative values from calibration

#Timestamp vs. Water Content, color = Treatment
ggplot(Sensor_Data, aes(x = Datetimes, y = WaterAmt, color = Treatment)) +
  geom_smooth(na.rm = T) + 
 # geom_point() +
  scale_y_continuous(limits = c(0.18, 0.45)) ##Removes negative values from calibration

#Timestamp vs. Water Content, color = Fallow YN
ggplot(Sensor_Data, aes(x = Datetimes, y = WaterAmt, color = Fallow_YN)) +
  geom_smooth(na.rm = T) + 
  #geom_point() +
  scale_y_continuous(limits = c(0.18, 0.45)) ##Removes negative values from calibration
```

```{r Weather Graphs, echo = T}
##Analyzing Weather Data
#Aggregating Daily Rainfall
daily_rain <- Weather_Data %>% 
  mutate(Date = as.Date(Datetimes)) %>%  #Extract the date part
  group_by(Date) %>% 
  summarise(daily_rainfall = sum(Rain...in, na.rm = T))
  
#print(daily_rain)

ggplot(daily_rain, aes(x = Date, y = daily_rainfall)) +
  geom_line(color = "blue", na.rm = T) +
  geom_point(color = "blue", na.rm = T) +
  labs(title = "UC Gill Tract 2023-24 Daily Rainfall",
       x = "Date",
       y = "Daily Rainfall (in)") +
  theme_minimal()


#Daily Temp High and Low
daily_temps <- Weather_Data %>% 
  mutate(Date = as.Date(Datetimes)) %>%  #Extract the date part
  group_by(Date) %>% 
  summarise(
    MinTemp = min(Temp....F, na.rm = T),
    MaxTemp = max(Temp....F, na.rm = T)
  )
#print(daily_temps)

#Reshaping Max & Min Temp dataframe
long_temps <- daily_temps %>% 
  pivot_longer(cols = c(MinTemp, MaxTemp),
               names_to = "TempType",
               values_to = "Temp.F")

long_temps$Temp.F <- as.numeric(long_temps$Temp.F)
#str(long_temps)

ggplot(long_temps, aes(x = Date, y = Temp.F, color = TempType)) +
  geom_line(aes(group = TempType), na.rm = T) +
  geom_point(na.rm = T) + # Add points to the line plot for better visibility
  labs(title = "UC Gill Tract 2023-24 Daily Minimum and Maximum Temperatures",
       x = "Date",
       y = "Temperature (°F)") +
  scale_color_manual(values = c("MinTemp" = "blue", "MaxTemp" = "red"),
                     labels = c("Minimum Temperature", "Maximum Temperature")) +
  theme_minimal()


```

```{r Biomass Data, echo = T}
#Adding in Yield Calculations
Biomass_Data <- Biomass_Data %>% 
  mutate(Yield = (Biomass.Weight..g.* 35.686))
#view(Biomass_Data)

#Yield Histogram
ggplot(Biomass_Data, aes(x = Harvest.Treatment, y = Yield)) +
  geom_hline(yintercept = 4500, color = "red", linetype = "dashed", size = 1) + ##SGMA CC Credit Criteria
  geom_boxplot(na.rm = T) +
  geom_dotplot(binaxis = 'y',
               stackdir = 'center',
               dotsize = 0.7) +
  labs(title = "Dry Yield Under Different Cover Crop Termination Timings",
       x = "Cover Crop Termination Timing",
       y = "Dry Yield (lbs/acre)")

#For 120 day data, which treatments reached 4500 lb/acre?
later_date_biomass <- Biomass_Data %>% 
  filter(Harvest.Treatment == "120 Day")

ggplot(later_date_biomass, aes(x = Treatment, y = Yield, color = Treatment)) +
  geom_hline(yintercept = 4500, color = "red", linetype = "dashed", size = 1) + ##SGMA CC Credit Criteria
  geom_boxplot(na.rm = T) +
  geom_dotplot(binaxis = 'y',
               stackdir = 'center',
               dotsize = 0.7) +
  labs(title = "120 Day Harvest Dry Yield by Treatment",
       x = "Treatment",
       y = "Dry Yield (lbs/acre)")
##Note: Only Rye-Mustard and Rye Mono CONSITENTLY reached over 4,500 lb/acre threshold. This was predicted as they were the most 'aggressive' growth mixes, but its amazing to see reflected in the data. Rye-Vetch had lowest out the treatments, even though rye here was planted at 80% of its mono, aka, vetch did really well but didn't accumulate biomass, likely because it grows out, not up. 
```

```{r Soilcore Data, echo = T}

#Plotting Soilcore GWC vs. Fallow_YN
ggplot(Soilcore_Data, aes(x = Treatment, y = GWC....)) +
  geom_boxplot(na.rm = T)

######NEEDS WORK########




```


```{r ET, echo = T}
#For Penman-Montieth calculation, need: https://www.rdocumentation.org/packages/Evapotranspiration/versions/1.16/topics/ET.PenmanMonteith
 #1. subdaily temp max and daily temp min
 #2. subdaily relative humidity in percentage
 #3. subdaily solar radiation in Megajoule per square meter (Rs), currently in W/square meter
 #4. subdaily wind speed in meter per second (uz), currently in mph


view(Weather_Data)



######NEEDS WORK########

```

```{r Notes for future directions, echo = T}
 ##DONE #1. What do the diff treatments look like in biomass? Is it significant? Does it represent greater N uptake?

#2. What does the drydown look like (post-April) for different treatments? Does soilcore data match soil sensor data?

#3. Can I use et models (combination, energy transfer) to distinguish between treatments? Apply Evapotranspiration Package (look at parameters)

#4. Tradeoffs: Planting early/term early to minimize water loss and protect groundwater (N scavenging), BUT irrigation would be needed. Would the irrigated water 'budget' be returned?

```
